# Generated by Django 2.2.24 on 2022-04-14 14:34

from django.db import migrations

def set_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.objects.update_or_create(
            set_new_building=flat.construction_year < 2015
        )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building)
    ]
